name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types:
      - closed
    branches:
      - master

  pull_request_target:
    types:
      - opened
      - synchronize

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read scripts version from file
        id: scripts-version
        run: echo "::set-output name=version::$(cat SCRIPTS_VERSION)"

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: docker/build-push-action@v5
        with:
          context: ./container
          push: true
          build-args: |
            BW_CLI_VERSION=${{ steps.version.outputs.version }}
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}-${{ steps.scripts-version.outputs.version }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with version and PR branch tag
        if: github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'pull_request_target' && github.event.action != 'closed'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64, linux/386, linux/arm/v7, linux/arm/v6
          context: ./container
          push: true
          build-args: |
            BW_CLI_VERSION=${{ steps.version.outputs.version }}
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}-${{ steps.scripts-version.outputs.version }}-${{ github.run_number }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
