name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./path/to/your/dir
          push: true
          build-args: |
            BW_CLI_VERSION=${{ steps.version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/your-image-name:${{ steps.version.outputs.version }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
