name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    types:
      - closed
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - synchronize
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag
        id: get-image-tag
        run: |
          if [ "$(git branch --show-current)" == "master" ]; then
            echo "tag=$(cat VERSION)-$(cat SCRIPTS_VERSION)" >> $GITHUB_OUTPUT
          else
            echo "tag=$(cat VERSION)-$(cat SCRIPTS_VERSION)-$(git branch --show-current)" >> $GITHUB_OUTPUT
          fi

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-architecture Docker image
        run: make container-build-and-push-multiarch VERSION_TAG="${{ steps.get-image-tag.outputs.tag }}"
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
