name: Publish Helm Chart

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Publish chart
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          make publish-chart
