{{- if and .Values.networkPolicyPodSelectors .Values.networkPolicyNamespaceSelectors }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: bitwarden
  name: external-secret-2-bw-cli
spec:
  podSelector:
    matchLabels:
      {{- include "bitwarden-cli-srv.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
      {{- range .Values.networkPolicyPodSelectors }}
      - podSelector:
          matchLabels:
            {{ . | nindent 12 }}
      {{- end }}
      {{- range .Values.networkPolicyNamespaceSelectors }}
      - namespaceSelector:
          matchLabels:
            {{ . | nindent 12 }}
      {{- end }}
{{- end }}
